[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Alex Lipscomb", email = "johnalipscomb@gmail.com"},
]
dependencies = [
    "discord-py>=2.2.2",
]
requires-python = ">=3.9"
license = {text = "MIT"}
