[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Alex Lipscomb", email = "johnalipscomb@gmail.com"},
]
dependencies = [
    "py-cord>=2.4.1",
]
requires-python = ">=3.9"
license = {text = "MIT"}
